### ISSUE TITLE
启动报 Dynamic require of "mars3d-cesium" is not supported

### ISSUE THREAD

**Issue by liseri** [marsgis/mars3d-vue-project-admin#2]
```
Uncaught Error: Dynamic require of "mars3d-cesium" is not supported
    at chunk-Q7IO5PSJ.js?v=bdbd3224:30:9
    at mars3d.js:10:101
    at node_modules/mars3d/dist/mars3d.js (mars3d.js:13:1)
    at __require2 (chunk-Q7IO5PSJ.js?v=bdbd3224:36:50)
    at dep:mars3d:1:16
```
版本是：3.5.0

将vite升到最新版本也不行

**Comment by muyao1987** [comment]
已修复
